### ISSUE TITLE
Problem in the project: Compare Recent reddit Karma

### ISSUE THREAD

**Issue by DigBick17** [jorgegonzalez/beginner-projects#177]
Is there even a way to get the number of karma received from one single post?
The most you can do is check a redditor's comment karma and link karma using PRAW.

 Here is the link to the project: [Compare Recent reddit Karma](https://github.com/jorgegonzalez/beginner-projects#compare-recent-reddit-karma)

**Comment by jorgegonzalez** [comment]
> If you go to a user's profile and add .json to the end of it, you can get the all sorts of Json data about the user (think of Json as a giant dictionary of smaller dictionaries and lists).
