### ISSUE TITLE
Existing solutions need to be deleted

### ISSUE THREAD

**Issue by JorgeGonzalez** [JorgeGonzalez/Beginner-Projects#18]
There are some solutions in certain project folders and they must be removed according to this repos new model. Please save those solutions in your own repos, and just add a link to them in the project READMEs.

**Comment by jrgz** [comment]
Just reminding everyone that has previously posted a solution to migrate them over to their own repositories or they will be deleted. When this issue reaches 30 days old, all old solutions will be purged. To clarify, only the python files in the project directories will be deleted.

**Comment by JarrettCoker** [comment]
New to source control and Github. Just curious, may I add my Java solution to one of your projects? How do I link them to my repo from your README?

**Comment by jrgz** [comment]
Yes, solutions in any language are allowed. Fork the repo, add your solution as a link in the respective project's README be editing it, then commit and push the changes. Let me know if you have any other questions.

**Comment by JarrettCoker** [comment]
Hey, thanks! I'm still getting used to things around here on github. Thank you for allowing me to contribute to this project. It's a great starting place for beginners like me. I think.. I think i just created a pull request. Not sure if that's the correct thing to do. Thanks for the help too!

**Comment by jrgz** [comment]
My intent for this repository was to host a series of very general projects (which were not created by me) for learners to complete in whatever programming language they are learning. And since we are on Github, this also gives learners a motivation or duty to learn Git as well.

[Here](http://chris.beams.io/posts/git-commit/) is a very popular article for you to learn more about Git. I also recommend [Codecademy's](https://www.codecademy.com/learn/learn-git) Git course. Good luck! And feel free to let me know if you have any other questions.

**Comment by JarrettCoker** [comment]
Alright, cool! My first successful pull request, sweet! Thanks for the learning resources, I'll look into those when I get back home next week.

**Comment by jrgz** [comment]
I want to remind everyone who has previously contributed a solution **in the form of a .py** file in the project directories that those files **will be deleted in 10 days** in order to comply with this repo's new model.

**Comment by JorgeGonzalez** [comment]
I want to remind everyone who has previously contributed a solution **in the form of a .py** file in the project directories that those files **will be deleted in 5 days** in order to comply with this repo's new model.

**Comment by JorgeGonzalez** [comment]
All old solutions have been moved into the `old` directory. I will create an issue soon to ask the specific writers of those solutions to make sure they are backed up before they are permanently deleted.
