### ISSUE TITLE
What is my number

### ISSUE THREAD

**Issue by AnonRandom** [JorgeGonzalez/Beginner-Projects#23]
In the "what is my number" problem there is a bit of an ambiguity with your conditions. 

In particular, in "the second to last digit is even" you should probably declare whether zero is allowed to be an even number because by just implementing the conditions you end up with two possible answers for which all conditions are true. The two answers are 503 and 523.

According to [Wikipedia](https://en.wikipedia.org/wiki/Parity_of_zero), zero is an even number. Likewise if you were to test by doing `x % 2 == 0` or `not x & 1` you would come to the same conclusion.

My implementation: http://pastebin.com/w2GhKki

Possible solutions could be to amend the condition by saying "the second to last digit is even and greater than 1" or adding the condition, "the sum of all the digits in the number is greater than 9".

**Comment by jrgz** [comment]
That's a good point. I didn't create these problems, but I apologize for the confusion. I will change the condition to "the second to last digit is even and greater than 1".

**Comment by jrgz** [comment]
Just made that change. Feel free to close this issue if that works for you. Let me know if you have any other questions or suggestions.
